# Projet d'équipe : vélos et vélos en libre-service à Montpellier
## Participants du groupes et leurs numéros étudiants ():

- **Sarih kaoutar** (22216094)
- **lucine bonnefont** (22108896)
- **naima radouan** (21900536)
- **kilian saint-chely** (22210432)

## Description:

## Rétro-Planning du Projet:
<<<<<<< HEAD


## Rétro-Planning du Projet de Partage de Vélos

| Date       |      Étape                                        | Description                                    |
|------------|----------------------------------------------|------------------------------------------------  |
| 16/10 - 20/10 | Analyse des données existantes              | Identifier et comprendre les besoins du projet.|
| 21/10 - 25/ | Collecte de données sur le trafic           | Rassembler les données nécessaires.             |
| 26/10 - 31/ | Nettoyage des données                       | Préparer les données pour l'analyse.           |
| 01/11 - 10/ | Analyse statistique des données             | Extraire des informations significatives.      |
| 11/11 - 20/ | Création des visualisations interactives    | Développer des graphiques et cartes.           |
| 21/11 - 05/ | Développement du site web                   | Créer une plateforme pour les visualisations.   |
| 06/12 - 12/| Préparation de la présentation finale       | Élaborer les diapositives et le discours.      |
| 13/12       | Présentation finale                          | Exposer les résultats du projet.               |


                                 
=======
>>>>>>> 9aa7f0bc22aeedee580cd2a5b54caf56c4d3153d
