---
title: "Flux de vélos à Montpellier"
date: "2024-10-25"
format: html
---

## Description des données:
- [Bike-sharing rides](https://data.montpellier3m.fr/dataset/courses-des-velos-velomagg-de-montpellier-mediterranee-metropole) :
Ce site nous offre des informations détaillées sur les flux enregistrés par les éco-compteurs installés dans la ville. Actualisées quotidiennement, ces données sont disponibles à la fois au niveau journalier et horaire, permettant une analyse précise des tendances de mobilité urbaine. Les formats fournis incluent CSV, JSON et GeoJSON, facilitant leur utilisation dans différents outils d’analyse et de visualisation. Une API permet également l’accès aux données horaires et historiques depuis janvier 2023, offrant une flexibilité accrue aux développeurs et chercheurs. Ces données sont cruciales pour planifier les infrastructures et améliorer les politiques de mobilité durable à Montpellier.  

- [Cyclist and pedestrian counting](https://data.montpellier3m.fr/dataset/comptages-velo-et-pieton-issus-des-compteurs-de-velo):
Ce lien nous fournit des informations précises sur les déplacements effectués. Ces données incluent les points de départ et d’arrivée des trajets ainsi que les horaires associés, permettant une analyse approfondie des habitudes de mobilité à vélo dans la métropole. Disponibles en formats CSV, JSON et GeoJSON, elles sont facilement exploitables pour divers outils d’analyse et de visualisation. Une API permet également d’accéder aux données en temps réel et à l’historique des trajets, offrant une grande flexibilité aux développeurs et chercheurs. Ces informations sont cruciales pour optimiser le service VéloMagg et améliorer les infrastructures cyclables à Montpellier.  


- [Open street map data](https://www.openstreetmap.org/#map=11/43.6000/3.8435):
Ce site nous présente un service de cartographie collaborative. En utilisant les coordonnées fournies (43.6000, 3.8435), la carte affiche une zone en France, probablement près de Montpellier. On peut y voir des routes, des bâtiments, des parcs et d'autres infrastructures, avec la possibilité de zoomer et de naviguer dans la région. OpenStreetMap permet aussi aux utilisateurs de contribuer à la cartographie en ajoutant des informations.


## 🎯Objectif du projet et résultat attendu:
Le but de ce projet est d'analyser les données ci-dessus afin de créer des visualisations, idéalement interactives, à travers un site web pour explorer ces données. Les résultats attendus incluent une carte interactive prédictive du trafic des vélos et une vidéo illustrant l'évolution des trajets.
Ce projet évalue les compétences en gestion de données, développement web, et collaboration en équipe via GitHub.

## Outils techniques utilisés:
- `VSCode` qui nous permet d'utiliser les outils suivants:
   - Python (avec Pandas, Matplotlib, Seaborn) pour le codage des cartes, du site web.
   - Quarto pour la création des documents dynamiques et interactifs ainsi que pour la création et le développement du site web.
   - (.css) pour la mise en page du site web, ou encore l'aesthétic de la vidéo.
   - HTML pour définir la structure et le contenu de chaque page du site web.
- `GitHub` pour la gestion de version et le travail collaboratif.
